### ISSUE TITLE
Error del Lint

### ISSUE THREAD

**Issue by ErickCSS** [midudev/la-velada-web-oficial#531]
# Pre-requisitos

- [ x ] Estoy corriendo la última versión.
- [ ] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Que cuando suba los cambios realizados a mi fork suba sin fallos

# Comportamiento actual
El lint me está dando error y no lo he tocado, más que una sola sección que toqué

<img width="749" alt="Screen Shot 2024-03-14 at 8 53 34 AM" src="https://github.com/midudev/la-velada-web-oficial/assets/60988586/81f358a1-bd38-41bf-91ec-1d4a1486ee8c">

# Información del bug (si corresponde)

## Pasos para reproducirlo

1. Paso 1
2. Paso 2

## Contexto

- Navegador: Firefox, Chrome, Safari, Microsoft Edge, Opera, etc.
- Versión del navegador: ---
- Sistema operativo: Windows, MacOS, Linux

## Logs de error (si corresponde)
Error: ESLint configuration in .eslintrc.cjs » @antfu/eslint-config is invalid:
	- Unexpected top-level property "GLOB_ALL_SRC".

Referenced from: /Users/erickcruz2/Desktop/Erick2/la-velada-web-oficial/.eslintrc.cjs
    at ConfigValidator.validateConfigSchema (/Users/erickcruz2/Desktop/Erick2/la-velada-web-oficial/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2177:19)
    at ConfigArrayFactory._normalizeConfigData (/Users/erickcruz2/Desktop/Erick2/la-velada-web-oficial/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3019:19)
    at ConfigArrayFactory._loadConfigData (/Users/erickcruz2/Desktop/Erick2/la-velada-web-oficial/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2984:21)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/erickcruz2/Desktop/Erick2/la-velada-web-oficial/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3285:21)
    at ConfigArrayFactory._loadExtends (/Users/erickcruz2/Desktop/Erick2/la-velada-web-oficial/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3156:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/erickcruz2/Desktop/Erick2/la-velada-web-oficial/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/erickcruz2/Desktop/Erick2/la-velada-web-oficial/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/erickcruz2/Desktop/Erick2/la-velada-web-oficial/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
husky - pre-commit script failed (code 1)

**Comment by AlejandroSuero** [comment]
Has añadido solo el archivo que has tocado `git add <ruta-del-archivo>` o has usado `git add .` o `git add - A`?

**Comment by midudev** [comment]
Mea culpa al actualizar una dependencia. Arreglado!

**Comment by ErickCSS** [comment]
@AlejandroSuero  He añadido las rutas que he arreglado, pero mi sigue saliendo el mismo error.

He quitado mis cambios, he actualizado mi fork para estar al día nuevamente, he vuelto a realizar los cambios y todavía me sigue dando el mismo error.

**Comment by AlejandroSuero** [comment]
> @midudev Sigo teniendo el mismo error y he seguido todos los pasos del CONTRIBUTING.md

Que archivo es el que estás editando? Para ver si puedo reproducirlo.

**Comment by ErickCSS** [comment]
SelectYourBoxer.astro y ColumnBoxer.astro

**Comment by AlejandroSuero** [comment]
> @AlejandroSuero SelectYourBoxer.astro y ColumnBoxer.astro

He hecho cambios y me pasa las pruebas. Comprueba que tu rama main y en la que estés trabajando estén sincronizadas, usar la version de node correcta, `pnpm install`.

Una cosa que hago yo es hacer `git fetch --all --prune` desde la `main` para limpiar lo innecesario y luego `git pull --rebase`.

Mira a ver si haciendo eso te funciona.

Porque parece fallo de la configuración de ESLINT pero ya está solucionado.

A mí antes no me linteaba ni los archivos, en teoría ya está arreglado.

**Comment by AlejandroSuero** [comment]
#532 Aquí se están arreglando errores, a lo mejor es alguno de los que tienes. También una opción es hacer `pnpm run lint` y `pnpm run format:check` para ver si hay algún fallo en los archivos en los que estás trabajando.

**Comment by ErickCSS** [comment]
Muchas gracias @AlejandroSuero

**Comment by AlejandroSuero** [comment]
Nada, espero haberte ayudado @ErickCSS
