### ISSUE TITLE
[Bug]: Cuando se cancela el iniciar sesión marca un error 500

### ISSUE THREAD

**Issue by javimata** [midudev/la-velada-web-oficial#963]
### Señala los requisitos cumplidos

- [X] Estoy corriendo la última versión.
- [X] He revisado si ya hay un issue creado con características similares.

### Comportamiento esperado

Enviar a alguna página del sitio sin mostrar un error

### Comportamiento actual

Muestra una pagina de error 500
https://github.com/midudev/la-velada-web-oficial/assets/2237207/d293ba28-cec5-4b0c-a74f-e12cc82f5ade

### Información del bug

Yo estoy usando en https://chefsito.vercel.app/ la misma app para el auth pero usando google como provider y me pasa lo mismo al cancelar el inicio de sesión

### Pasos para reproducirlo

1- Dar click en iniciar sesión
2- Dar click en cancelar (confirmar)

### ¿En qué navegadores encuentras el problema?

Chrome

**Comment by AlejandroSuero** [comment]
@javimata Por lo que he estado probando en local, lanza el siguiente error:

```bash
TypeError: immutable
    at _Headers.delete (node:internal/deps/undici/undici:2356:17)
    at /path/to/repo/la-velada-web-oficial/node_modules/.pnpm/auth-astro@4.1.1_@auth+core@0.18.6_astro@4.8.6_@types+node@20.12.11_lightningcss@1.25.0_terse_nde6kmxe26vvgnos6ypz2whpmu/node_modules/auth-astro/server.ts:58:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.GET (/path/to/repo/la-velada-web-oficial/node_modules/.pnpm/auth-astro@4.1.1_@auth+core@0.18.6_astro@4.8.6_@types+node@20.12.11_lightningcss@1.25.0_terse_nde6kmxe26vvgnos6ypz2whpmu/node_modules/auth-astro/server.ts:94:11)
    at async renderEndpoint (file:////path/to/repo/la-velada-web-oficial/node_modules/.pnpm/astro@4.8.6_@types+node@20.12.11_lightningcss@1.25.0_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/runtime/server/endpoint.js:34:20)
    at async callMiddleware (file:///path/to/repo/la-velada-web-oficial/node_modules/.pnpm/astro@4.8.6_@types+node@20.12.11_lightningcss@1.25.0_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/core/middleware/callMiddleware.js:21:10)
    at async RenderContext.render (file:///path/to/repo/la-velada-web-oficial/node_modules/.pnpm/astro@4.8.6_@types+node@20.12.11_lightningcss@1.25.0_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/core/render-context.js:148:22)
    at async handleRoute (file:///path/to/repo/la-velada-web-oficial/node_modules/.pnpm/astro@4.8.6_@types+node@20.12.11_l

ightningcss@1.25.0_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/vite-plugin-astro-server/route.js:209:18)
    at async run (file:///path/to/repo/la-velada-web-oficial/node_modules/.pnpm/astro@4.8.6_@types+node@20.12.11_lightningcss@1.25.0_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/vite-plugin-astro-server/request.js:40:14)
    at async runWithErrorHandling (file:///path/to/repo/la-velada-web-oficial/node_modules/.pnpm/astro@4.8.6_@types+node@20.12.11_lightningcss@1.25.0_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/vite-plugin-astro-server/controller.js:64:5)
```

Error `inmutable` en `auth-astro/server:58:16` -> "Borrar los headers `Set-Cookie`"

Full URL con el error:
```txt
https://lavelada.es/api/auth/callback/twitch?error=access_denied&error_description=The+user+denied+you+access
```

![Screenshot 2024-06-11 at 23 58 51](https://github.com/midudev/la-velada-web-oficial/assets/71392160/75256f20-76f6-442e-ae5d-4a4a5479a284)

Aún así, la página en sí no cae, simplemente la ventana en la que se hace la autorización. También se puede volver a autorizar sin problemas. En local sí que cae, pero recargando se va el error.

https://github.com/midudev/la-velada-web-oficial/assets/71392160/2e8902bf-d416-4feb-821c-303bc38d229e

No sé si alguien o @midudev sabrá más de este tema por si se puede hacer algo, pero al no ser bloquear la página propiamente y al estar en una ventana externa, he intentado loggear la session en `src/pages/auth/twitch` pero al menos en local, no he conseguido sacar nada.

**Comment by javimata** [comment]
En el repo oficial me ayudaron con la respuesta, no la he probado aun

https://github.com/nowaythatworked/auth-astro/commit/315b6f94d06d2ece05e081043c03c35ea6c251a4

**Comment by AlejandroSuero** [comment]
@javimata iba a hacerle yo una PR porque modifiqué el archivo `node_modules/auth-astro/server.ts` de una manera parecida.

https://github.com/midudev/la-velada-web-oficial/assets/71392160/3b1a5af9-c617-4b46-bf09-24d6fa8e34b9

Así es como quedaría, si le das a iniciar con twitch de nuevo, se repetirá el proceso.

**Comment by AlejandroSuero** [comment]
@javimata he actualizado la dependencia de `auth-astro` en la PR enlazada.
